version: '3'


services:
  db:
    image: mysql:5.7
    volumes:
      - ./docker/data:/var/lib/checkmoney/data
    environment:
      - MYSQL_DATABASE=checkmoney
      - MYSQL_USER=check_money
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_PASSWORD=1111
      - TZ=Asia/Seoul
    ports:
      - '3306:3306'
    command:
      - --explicit_defaults_for_timestamp=true
  django:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - DJANGO_DB_HOST=db
    ports:
      - "8000:8000"
    command: bash -c "
        python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./:/app/
    restart: always
    depends_on:
      - db
