# Generated by Django 3.2.9 on 2021-12-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_category', '0001_initial'),
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_logs', to='cashbook.cashbook')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='log_category.expensecategory')),
            ],
            options={
                'db_table': 'expense_log',
            },
        ),
        migrations.CreateModel(
            name='DepositLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_logs', to='cashbook.cashbook')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='log_category.depositcategory')),
            ],
            options={
                'db_table': 'deposit_log',
            },
        ),
    ]
